# DeltaCode - Unreal Engine Code Helper
# Copyright (c) 2026 Andrew Nicholas
#
# This program is free software: you can redistribute
# it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software
# Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dc_create_ai_assets.py — bootstrap the BehaviorTree + Blackboard assets
# that ADCEnemyAIController needs at possession time, and wire them into
# B_DC_EnemyBase.
#
# The C++ AI stack (ADCEnemyAIController + the 5 BT tasks under Source/AI/
# + the DCAIBlackboardKeys namespace) ships with the plugin. What's missing
# on a fresh project is the BT/BB uasset files those tasks run against.
# This script fills that gap: idempotent, safe to re-run on every Danger
# Zone build. Existing assets are detected and reused.
#
# Verbose logging at every step so the Output Log shows exactly which part
# succeeded or skipped.

import unreal

# ─── CONSTANTS ───────────────────────────────────────────────────────────────

_AI_PACKAGE_PATH = "/Game/DeltaCode/AI"
_BB_NAME         = "BB_DC_Enemy_Default"
_BT_NAME         = "BT_DC_Enemy"
_BP_PATH         = "/Game/DeltaCode/Core/B_DC_EnemyBase"

# Lyra-parented enemy generated by dc_danger_zone._create_lyra_enemy_blueprint
# when Lyra is detected. We wire its BehaviorTree BP variable here on the same
# pass that wires B_DC_EnemyBase, so both enemy classes pick up the same BT.
_LYRA_BP_PATH = "/Game/DeltaCode/Core/B_DC_LyraEnemyBase"

_BB_FULL_PATH = f"{_AI_PACKAGE_PATH}/{_BB_NAME}"
_BT_FULL_PATH = f"{_AI_PACKAGE_PATH}/{_BT_NAME}"

# Pre-authored BT template shipped with the plugin. Duplicated on demand
# into /Game/DeltaCode/AI/ so every project gets a working Selector-root
# + WanderFromHome task graph without per-project manual wiring that Python
# can't automate (the BT editor regenerates runtime nodes from the UEdGraph
# on save, which is not Python-authorable).
_BT_TEMPLATE_PATH = "/DeltaCode/DeltaCode/AI/BT_DC_Enemy_Template"

# ─── LOGGING HELPERS ─────────────────────────────────────────────────────────

def _log(msg):  unreal.log(f"DeltaCode[AI]: {msg}")
def _warn(msg): unreal.log_warning(f"DeltaCode[AI]: {msg}")
def _err(msg):  unreal.log_error(f"DeltaCode[AI]: {msg}")


# ─── BLACKBOARD ──────────────────────────────────────────────────────────────

def _make_bb_entry(owner_asset, entry_name, key_type_class, base_class=None):
    """Construct an FBlackboardEntry with a freshly instanced key-type subobject.

    The key-type subobject is outered to the BlackboardData asset so it
    serialises alongside the asset and survives reloads.
    """
    entry = unreal.BlackboardEntry()
    entry.set_editor_property("entry_name", entry_name)
    kt = unreal.new_object(key_type_class, owner_asset)
    if base_class is not None:
        kt.set_editor_property("base_class", base_class)
    entry.set_editor_property("key_type", kt)
    return entry


def _create_blackboard():
    """Create BB_DC_Enemy_Default with the 4 keys DCEnemyAIController expects."""
    if unreal.EditorAssetLibrary.does_asset_exist(_BB_FULL_PATH):
        _log(f"Blackboard already exists: {_BB_FULL_PATH}")
        return unreal.load_asset(_BB_FULL_PATH)

    _log(f"Creating blackboard {_BB_FULL_PATH} ...")
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    bb = asset_tools.create_asset(
        _BB_NAME, _AI_PACKAGE_PATH, unreal.BlackboardData, None)
    if bb is None:
        _err(f"asset_tools.create_asset returned None for {_BB_NAME}")
        return None

    try:
        entries = [
            _make_bb_entry(bb, "TargetActor",
                           unreal.BlackboardKeyType_Object, unreal.Actor),
            _make_bb_entry(bb, "LastKnownLocation",
                           unreal.BlackboardKeyType_Vector),
            _make_bb_entry(bb, "HomeLocation",
                           unreal.BlackboardKeyType_Vector),
            _make_bb_entry(bb, "bIsInvestigating",
                           unreal.BlackboardKeyType_Bool),
        ]
        bb.set_editor_property("keys", entries)
        _log("Keys set: TargetActor (Object:Actor), LastKnownLocation (Vector), "
             "HomeLocation (Vector), bIsInvestigating (Bool)")
    except Exception as e:
        _warn(f"Failed to populate blackboard keys — {e}. "
              f"Open {_BB_NAME} and add keys manually.")

    # save_loaded_asset persists the live in-memory object — save_asset(path)
    # is load-then-save and discards the keys we just set in memory, which is
    # why BB_DC_Enemy_Default previously shipped with only SelfActor.
    unreal.EditorAssetLibrary.save_loaded_asset(bb)
    _log(f"Saved {_BB_FULL_PATH}")
    return bb


# ─── BEHAVIOR TREE ───────────────────────────────────────────────────────────

def _wire_blackboard(bt_full_path, bb_full_path):
    """Wire BT.BlackboardAsset via the C++ UDCAIEditorBridge.

    UBehaviorTree::BlackboardAsset is protected in UE5.7+, so Python's
    set_editor_property cannot reach it (the access check honours the C++
    access modifier). The bridge bypasses this by using FObjectProperty
    reflection, which is a data-level operation unaffected by `protected`.

    Returns True iff the bridge reports success. Failures are logged but
    don't raise — the caller decides whether to abort or continue.

    Return-shape note: UE Python wraps UFUNCTIONs with output parameters by
    returning a tuple. For this signature the empirical shape on 5.7 is
    longer than the (ok, msg) 2-tuple one might expect — by-ref `const
    FString&` inputs are surfaced alongside the actual out param. We unpack
    defensively: first element is the bool return, last element is the
    OutMessage string. Authoritative log record lives on the C++ side via
    UE_LOG(LogDCAIEditorBridge), so a missed Python message is cosmetic.
    """
    try:
        result = unreal.DCAIEditorBridge.set_behavior_tree_blackboard(
            bt_full_path, bb_full_path)
        if isinstance(result, tuple):
            ok = bool(result[0])
            msg = str(result[-1]) if len(result) > 1 else ""
        else:
            ok = bool(result)
            msg = ""
        if ok:
            _log(f"BlackboardAsset wired via bridge: {msg}")
        else:
            _err(f"DCAIEditorBridge failed: {msg}")
        return ok
    except AttributeError:
        _err("unreal.DCAIEditorBridge not registered — rebuild the plugin "
             "and restart the editor so the new UCLASS is reflected.")
        return False
    except Exception as e:
        _err(f"DCAIEditorBridge call raised: {e}")
        return False


def _create_behavior_tree(bb_asset):
    """Duplicate the plugin's pre-authored BT template into /Game/DeltaCode/AI/
    and wire its BlackboardAsset.

    We ship a pre-authored template because Python can't reliably write to a
    BehaviorTree's UEdGraph — the BT editor's compile step regenerates runtime
    nodes from the editor graph on save, wiping any new_object()-created
    RootNode/children set via set_editor_property. Duplication preserves the
    editor graph (Selector root + WanderFromHome task) baked into the template,
    and set_editor_property('blackboard_asset', ...) survives the compile step
    because it's a simple UPROPERTY on the BT asset.
    """
    # Self-heal path: a prior run may have produced a BT with the BB
    # reference dropped (UE's duplicate_asset can null external refs).
    # If we find the BT already exists, route the rewire through the
    # bridge — the BlackboardAsset property is protected in UE5.7+ so
    # set_editor_property cannot reach it.
    if unreal.EditorAssetLibrary.does_asset_exist(_BT_FULL_PATH):
        existing = unreal.load_asset(_BT_FULL_PATH)
        if existing is not None and bb_asset is not None:
            # We cannot cheaply detect "BT already wired correctly" because
            # the getter is also gated when the underlying property is
            # protected — calling the bridge unconditionally is idempotent
            # (writing the same value is a no-op the editor handles).
            if _wire_blackboard(_BT_FULL_PATH, _BB_FULL_PATH):
                _log(f"Existing BT at {_BT_FULL_PATH} confirmed wired to "
                     f"{_BB_NAME}")
        return existing

    if not unreal.EditorAssetLibrary.does_asset_exist(_BT_TEMPLATE_PATH):
        _err(f"Template BT not found at {_BT_TEMPLATE_PATH} — plugin may be "
             f"misinstalled or the template asset was deleted. Restore it "
             f"from source control, then re-run Build Mission.")
        return None

    _log(f"Duplicating {_BT_TEMPLATE_PATH} → {_BT_FULL_PATH}")
    bt = unreal.EditorAssetLibrary.duplicate_asset(
        _BT_TEMPLATE_PATH, _BT_FULL_PATH)
    if bt is None:
        _err(f"duplicate_asset returned None for {_BT_TEMPLATE_PATH}")
        return None

    if bb_asset is not None:
        # Bridge writes + saves in one call. No need for a separate
        # save_loaded_asset step here.
        _wire_blackboard(_BT_FULL_PATH, _BB_FULL_PATH)
    else:
        _warn("Blackboard asset is None — BT will not run at possession time.")
        unreal.EditorAssetLibrary.save_loaded_asset(bt)

    return bt


# ─── BLUEPRINT WIRING ────────────────────────────────────────────────────────

def _wire_enemy_blueprint(bt_asset):
    """Set B_DC_EnemyBase.BehaviorTree default so possession picks up the tree."""
    if bt_asset is None:
        _warn("No BT asset available — skipping B_DC_EnemyBase wiring.")
        return

    if not unreal.EditorAssetLibrary.does_asset_exist(_BP_PATH):
        _warn(f"{_BP_PATH} does not exist yet. "
              f"Run create_core_blueprints() first; wiring will pick up on the "
              f"next Danger Zone run.")
        return

    bp = unreal.load_asset(_BP_PATH)
    if bp is None:
        _err(f"load_asset returned None for {_BP_PATH}")
        return

    try:
        gen_class = bp.generated_class()
        cdo = unreal.get_default_object(gen_class)

        current = None
        try:
            current = cdo.get_editor_property("behavior_tree")
        except Exception:
            pass
        if current == bt_asset:
            _log(f"{_BP_PATH}.BehaviorTree already → {_BT_NAME}, no-op.")
            return

        cdo.set_editor_property("behavior_tree", bt_asset)
        _log(f"Set {_BP_PATH}.BehaviorTree → {_BT_NAME}")

        try:
            unreal.BlueprintEditorLibrary.compile_blueprint(bp)
            _log(f"Recompiled {_BP_PATH}")
        except Exception as e:
            _warn(f"compile_blueprint failed on {_BP_PATH} — {e}")

        unreal.EditorAssetLibrary.save_asset(_BP_PATH)
        _log(f"Saved {_BP_PATH}")
    except Exception as e:
        _err(f"Failed to set BehaviorTree default on {_BP_PATH} — {e}")


def _wire_lyra_enemy_blueprint(bt_asset):
    """Set BehaviorTree on the UDCEnemyAIData component template inside
    B_DC_LyraEnemyBase. DCEnemyAIController falls back to
    FindComponentByClass<UDCEnemyAIData>() when IDCEnemyAIPawn returns null,
    so this is what wires the Lyra-parented enemy to the shared BT/BB pair.

    Skipped silently if B_DC_LyraEnemyBase doesn't exist (non-Lyra project,
    or Lyra detected but BP creation failed earlier).
    """
    if bt_asset is None:
        _warn("No BT asset available — skipping B_DC_LyraEnemyBase wiring.")
        return

    if not unreal.EditorAssetLibrary.does_asset_exist(_LYRA_BP_PATH):
        _log(f"{_LYRA_BP_PATH} not present — skipping (Lyra not detected, "
             f"or BP creation deferred).")
        return

    bp = unreal.load_asset(_LYRA_BP_PATH)
    if bp is None:
        _err(f"load_asset returned None for {_LYRA_BP_PATH}")
        return

    try:
        # Locate the DCEnemyAIData component template via SubobjectDataSubsystem.
        # The legacy SimpleConstructionScript UPROPERTY isn't script-reflected on
        # UBlueprint (no BlueprintReadWrite specifier), so get_editor_property
        # for it always fails — the subsystem is the only path that works from
        # Python in UE5+.
        sub = unreal.get_engine_subsystem(unreal.SubobjectDataSubsystem)
        if sub is None:
            _err("SubobjectDataSubsystem unavailable — cannot wire "
                 "DCEnemyAIData.")
            return

        handles = sub.k2_gather_subobject_data_for_blueprint(bp)
        target_template = None
        for h in handles:
            data = sub.k2_find_subobject_data_from_handle(h)
            if data is None:
                continue
            obj = data.get_object()
            if obj is not None and isinstance(obj, unreal.DCEnemyAIData):
                target_template = obj
                break

        if target_template is None:
            _warn(f"{_LYRA_BP_PATH}: no DCEnemyAIData component found. The BP "
                  f"may have been created before component-add was working — "
                  f"delete {_LYRA_BP_PATH} and re-run Build Mission to "
                  f"regenerate.")
            return

        current = target_template.get_editor_property('behavior_tree')
        if current == bt_asset:
            _log(f"{_LYRA_BP_PATH}.DCEnemyAIData.BehaviorTree already → "
                 f"{_BT_NAME}, no-op.")
            return

        target_template.set_editor_property('behavior_tree', bt_asset)
        _log(f"Set {_LYRA_BP_PATH}.DCEnemyAIData.BehaviorTree → {_BT_NAME}")

        try:
            unreal.BlueprintEditorLibrary.compile_blueprint(bp)
        except Exception as e:
            _warn(f"compile_blueprint failed on {_LYRA_BP_PATH} — {e}")

        unreal.EditorAssetLibrary.save_asset(_LYRA_BP_PATH)
        _log(f"Saved {_LYRA_BP_PATH}")
    except Exception as e:
        _err(f"Failed to wire BT into {_LYRA_BP_PATH} — {e}")


# ─── ENTRY POINT ─────────────────────────────────────────────────────────────

def dc_create_ai_assets():
    """Ensure BT_DC_Enemy + BB_DC_Enemy_Default exist, wired into B_DC_EnemyBase
    AND B_DC_LyraEnemyBase (when present).

    Called from run_danger_zone() on every Build Mission. Idempotent — skips
    assets that already exist and re-wires each BP only if its current
    BehaviorTree default differs.
    """
    _log("=" * 60)
    _log("Bootstrapping enemy AI assets")
    bb = _create_blackboard()
    bt = _create_behavior_tree(bb)
    _wire_enemy_blueprint(bt)
    _wire_lyra_enemy_blueprint(bt)
    _log("Bootstrap complete")
    _log("=" * 60)


if __name__ == "__main__":
    dc_create_ai_assets()
